### ISSUE TITLE
LOL DİL DEĞİŞTİRME 

### ISSUE THREAD

**Issue by M5TF** [ForGameProgrammer/League-Language-Changer#1]
merhabalar şuan yaptığınız uygulama ile dil değiştirmek istedim ama korece yerine japonca bunun çaresi var mıdır korece için ?

**Comment by ForGameProgrammer** [comment]
Bir bakayım

**Comment by ForGameProgrammer** [comment]
Evet, dediğiniz gibi Korece eklememişim. Bir kaç saat içerisinde düzeltmeye çalışacağım

**Comment by ForGameProgrammer** [comment]
Uygulamayı Güncelledim Fakat Araştırmalarıma Göre Riot Games Korece Dil Desteği Kore Serverı Haricinde Sunmuyor :/ Buna yapabileceğim Birşey Bulunmuyor
